import type { Metadata } from "next";
import Script from 'next/script';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="nav-trap" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: `(
          function(){
            try{
              // wrap fetch to log /auth/me responses
              const origFetch = window.fetch.bind(window);
              window.fetch = function(...args){
                const p = origFetch.apply(this, args);
                p.then(res => {
                  try{
                    const pathname = new URL(res.url, location.origin).pathname;
                    if (pathname === '/auth/me'){
                      console.debug('[NavTrap] /auth/me status', res.status, 'url:', res.url);
                      if (res.status === 401){
                        console.warn('[NavTrap] /auth/me returned 401 - ABORTING NAVIGATION NEXT');
                        console.trace('[NavTrap] Trace for /auth/me -> 401');
                        // Set a global flag to block the next few seconds of navigation?
                        window.__blockNavUntil = Date.now() + 2000;
                      }
                    }
                  }catch(e){}
                }).catch(()=>{});
                return p;
              };

              // Update traceIfDashboard to allow block via flag
              const traceIfDashboard = (where, url) => {
                try{
                  const p = typeof url === 'string' ? new URL(url, location.origin).pathname : (url && url.pathname) || '';
                  if (p === '/dashboard'){
                    if (window.__blockNavUntil && Date.now() < window.__blockNavUntil) {
                       console.warn('[NavTrap] Hard blocked ' + where + ' to /dashboard due to recent 401');
                       console.trace('[NavTrap] Trace for hard blocked ' + where + ' to /dashboard');
                       return true;
                    }
                    console.warn('[NavTrap] Blocked early ' + where + ' to /dashboard');
                    console.trace('[NavTrap] Trace for blocked ' + where + ' to /dashboard');
                    return true;
                  }
                }catch(e){}
                return false;
              };
            }catch(e){ console.error('[NavTrap] init error', e); }
          }
        )()` }} />
        {children}
      </body>
    </html>
  );
}
